In [180]:
import numpy as np
import scipy.linalg


In [181]:
states = {0:'Sunny', 1:'Cloudy', 2:'Rainy'}   # Create a Dictionary with the states
A = np.array([[0.8,0.2,0],[0.4,0.4,0.2],[0.2,0.6,0.2]])   # A is the Transition matrix
A

array([[0.8, 0.2, 0. ],
       [0.4, 0.4, 0.2],
       [0.2, 0.6, 0.2]])

2(b) Write up a general purpose simulator for the state transition matrix

In [182]:
n = 30   # No. of iterations
start_state  = np.random.randint(3)   # Randomaly select start state
curr_state = start_state
print(f"{states[curr_state]} --> ", end="")   # Print first state

while n>0:
    curr_state = np.random.choice([0, 1, 2], p=A[curr_state])   # Set current state randomly based on the probabilities provieded in the Transition Matrix.
    print(f"{states[curr_state]} --> ", end="")   # Print current state
    n = n-1
print('END')



Rainy --> Cloudy --> Cloudy --> Cloudy --> Cloudy --> Cloudy --> Cloudy --> Cloudy --> Rainy --> Cloudy --> Cloudy --> Cloudy --> Cloudy --> Cloudy --> Sunny --> Sunny --> Sunny --> Sunny --> Cloudy --> Cloudy --> Rainy --> Cloudy --> Rainy --> Cloudy --> Cloudy --> Sunny --> Sunny --> Cloudy --> Rainy --> Rainy --> Cloudy --> END


In [183]:
# Sunny  = 9/14 = 0.6428571428571429
# Cloudy = 2/7  = 0.2857142857142857
# Rainy  = 1/14 = 0.0714285714285714

steps = 10**6
# start_state = 0
# curr_state = start_state
# pi = np.array([0, 0, 0])
# pi[start_state] = 1

# i = 0
pi2 = np.array([[0,0,0], [0,0,0], [0,0,0]])
for j in range(0,3):
    start_state = 0
    curr_state = start_state
    pi = np.array([0, 0, 0])
    pi[start_state] = 1
    i = 0
    while i<steps:
        curr_state = np.random.choice([0,1,2], p=A[curr_state])
        pi[curr_state]+=1
        i +=1
    pi2[j] = pi
    print("π = ", pi/steps)

column_averages = np.mean(pi2, axis=0)

print("Average of each column:")
print(column_averages/steps)


π =  [0.643826 0.285048 0.071127]
π =  [0.642291 0.285909 0.071801]
π =  [0.642365 0.286416 0.07122 ]
Average of each column:
[0.64282733 0.285791   0.07138267]


In [184]:
steps = 10**5
start_state = 0
curr_state = start_state
pi = np.array([0, 0, 0])
pi[start_state] = 1
temp_pi = np.array([0, 0, 0])
i = 0
while i<steps:
    if pi[0]!=0:
        temp_pi = pi/i
    curr_state = np.random.choice([0,1,2], p=A[curr_state])
    pi[curr_state]+=1
    i +=1
    # print(temp_pi,pi)
    if temp_pi[0] == pi[0]/i:
        break

print(i)
print("π = ", pi/steps, temp_pi)

4
π =  [4.e-05 1.e-05 0.e+00] [1.         0.33333333 0.        ]


C:\Users\ROHIT\AppData\Local\Temp\ipykernel_7868\1477613802.py:10: RuntimeWarning: divide by zero encountered in divide
  temp_pi = pi/i
C:\Users\ROHIT\AppData\Local\Temp\ipykernel_7868\1477613802.py:10: RuntimeWarning: invalid value encountered in divide
  temp_pi = pi/i


In [185]:
# Sunny  = 9/14 = 0.6428571428571429
# Cloudy = 2/7  = 0.2857142857142857
# Rainy  = 1/14 = 0.0714285714285714

num_simulations = 100
num_transitions = 100000

stationary_distribution = np.zeros(3)

for _ in range(num_simulations):
    start_state = 0
    curr_state = start_state
    pi = np.array([0, 0, 0])
    pi[start_state] = 1

    for _ in range(num_transitions):
        curr_state = np.random.choice([0, 1, 2], p=A[curr_state])
        pi[curr_state] += 1
    stationary_distribution += pi / num_transitions

stationary_distribution /= num_simulations

print("Stationary Distribution:")
print(stationary_distribution)


Stationary Distribution:
[0.6430879 0.285618  0.0713041]


In [186]:
values, left = scipy.linalg.eig(A, right = False, left = True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

pi = left[:,0]
pi_normalized = [(x/np.sum(pi)).real for x in pi]
pi_normalized

left eigen vectors = 
 [[-0.90913729 -0.81251992  0.23258782]
 [-0.40406102  0.47596315 -0.79410449]
 [-0.10101525  0.33655677  0.56151667]] 

eigen values = 
 [ 1.        +0.j  0.48284271+0.j -0.08284271+0.j]


[0.6428571428571426, 0.28571428571428586, 0.07142857142857145]